Enhancements to the apiWriter object. Callback can be a function, or an object.  If callback is a function, it is assumed to be a success handler, and callback is called upon successful completion of the operation. If callback is an object, you can specify a success and an error handler in the following form.
var callback = {
	success: function(msg){
		//Handle success
		},
	error: function(errMsg){
		//Handle Error	
	}
};